---
# tasks file for php5-nginx (bridging-role)

- include: install-php-fpm.yml
  tags:
    - BARC_INSTALL
    - BARC_INSTALL_PACKAGES

- include: configure-sapi-fpm.yml
  tags:
    - BARC_CONFIGURE
    - BARC_CONFIGURE_PACKAGE

- include: register-role.yml
  tags:
    - BARC_ROLE_REGISTRATION
